# Test against this version of Node.js
environment:
  nodejs_version: "6.9.1"
  install_berry_perl: "cmd /C git clone https://github.com/stevieb9/berrybrew && cd berrybrew/bin && berrybrew.exe install %version% && berrybrew.exe switch %version%"
  install_active_perl: "cmd /C choco install activeperl -version %version%"
  install_berry_padwalker: "cmd /C cpanm PadWalker"
  install_active_padwalker: "cmd /C ppm install PadWalker"

  matrix:
    # http://strawberryperl.com/
    - install_perl: "%install_berry_perl%"
      install_padwalker: "%install_berry_padwalker%"
      version: "5.24.1_64"
    - install_perl: "%install_berry_perl%"
      install_padwalker: "%install_berry_padwalker%"
      version: "5.22.3_64"
    - install_perl: "%install_berry_perl%"
      install_padwalker: "%install_berry_padwalker%"
      version: "5.20.3_64"
    - install_perl: "%install_berry_perl%"
      install_padwalker: "%install_berry_padwalker%"
      version: "5.18.4_64"
    - install_perl: "%install_berry_perl%"
      install_padwalker: "%install_berry_padwalker%"
      version: "5.16.3_64"
    # https://chocolatey.org/packages/ActivePerl
    - install_perl: "%install_active_perl%"
      install_padwalker: "%install_active_padwalker%"
      version: "5.24.1.2402"
    - install_perl: "%install_active_perl%"
      install_padwalker: "%install_active_padwalker%"
      version: "5.22.0.2200"
    - install_perl: "%install_active_perl%"
      install_padwalker: "%install_active_padwalker%"
      version: "5.18.2.1801"
    - install_perl: "%install_active_perl%"
      install_padwalker: "%install_active_padwalker%"
      version: "5.14.2.2"

# Install scripts. (runs after repo cloning)
install:
  # Install perl
  - cmd: "%install_perl%"
  # Make sure we are in project root
  - cmd: "cd %APPVEYOR_BUILD_FOLDER%"
  # Set path for berrybrew
  - SET PATH=C:\berrybrew\%version%\c\bin;C:\berrybrew\%version%\perl\site\bin;C:\berrybrew\%version%\perl\bin;%PATH%
  # Install PadWalker
  - cmd: "%install_padwalker%"
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - perl --version
  # run tests
  - npm test

# Don't actually build.
build: off
